---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - vpc-p01usw2stage-v7-fgczvvgqf5h7zwmoicajtnblua.us-west-2.es.amazonaws.com
  port: 443
  #url_prefix:
  use_ssl: True
  #certificate:
  #client_cert:
  #client_key:
  ssl_no_validate: False
  #http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: DEBUG
  logfile: /var/log/curator.log
  logformat: default
  blacklist: ["elasticsearch", "urllib3"]
