actions:
  1:
    description: >-
      Snapshot scanhistories from elastico to aws es
    action: snapshot
    description: >-
      Snapshot selected indices to 'repository' with the snapshot name or name
      pattern in 'name'.  Use all other options as assigned
    options:
      repository: stage-elastico
      # Leaving name blank will result in the default 'curator-%Y%m%d%H%M%S'
      name: scanhistories-202003
      wait_for_completion: True
      max_wait: 3600
      wait_interval: 10
    filters:
    - filtertype: none