---
- hosts: ip-10-11-63-217.us-east-2.compute.internal
  remote_user: ubuntu
  become: yes
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: ~/.ssh/athena-devops.pem
  roles:
  - docker
