---
# tasks file for cache_queue
- name: Create the host security group
  ec2_group:
    name: "{{ ec2_sg_name }}"
    description: Security Group for new host
    region: "{{ ec2_region }}"
    vpc_id: "{{ vpc_id }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 27017
        to_port: 27017
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 5672
        to_port: 5672
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 15672
        to_port: 15672
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 15674
        to_port: 15674
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: launch the new ec2 instance
  ec2:
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    group: "{{ ec2_sg_name }}"
    instance_type: "{{ ec2_instance_type }}"
    instance_profile_name: "{{ ec2_profile }}"
    image: "{{ ec2_image }}"
    wait: true
    region: "{{ ec2_region }}"
    keypair: "{{ ec2_keypair }}"
    count: 1
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 20
        delete_on_termination: yes
    user_data: "{{ lookup('template', 'user_data.j2') }}"
    instance_tags:
      Name: edulogvn-athena-queue-cache-base
  register: ec2

- name: wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    state: started
  with_items: "{{ ec2.instances }}"

- name: wait for service mongodb to be up and complete
  wait_for:
    host: "{{ item.public_ip }}"
    port: 27017
    state: started
  with_items: "{{ ec2.instances }}"

- name: wait for service rabbitmq to be up and complete
  wait_for:
    host: "{{ item.public_ip }}"
    port: 5672
    state: started
  with_items: "{{ ec2.instances }}"

- name: wait for rabbitmq websocket to be up and complete
  wait_for:
    host: "{{ item.public_ip }}"
    port: 15674
    state: started
  with_items: "{{ ec2.instances }}"
